name       : aom
version    : 3.3.0
release    : 12
source     :
    - git|https://aomedia.googlesource.com/aom : v3.3.0
license    :
    - AOMPL-1.0 # https://aomedia.org/license/patent-license/
    - BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 codec
description: |
    The Alliance for Open Media’s focus is to deliver a next-generation video format that is:

    - Interoperable and open;
    - Optimized for the Internet;
    - Scalable to any modern device at any bandwidth;
    - Designed with a low computational footprint and optimized for hardware;
    - Capable of consistent, highest-quality, real-time video delivery; and
    - Flexible for both commercial and non-commercial content, including user-generated content.
builddeps  :
    - yasm
setup      : |
    sed 's|/lib|/lib64|g' -i build/cmake/pkg_config.cmake

    %cmake_ninja -DBUILD_SHARED_LIBS=1 -DENABLE_TESTS=0
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm -v $installdir/usr/lib64/libaom.a
